### ISSUE TITLE
哥们，虽然你这个内容和控件写得不错，但是.....

### ISSUE THREAD

**Issue by taany6210** [123lxw123/VideoWorld_Android#1]
下拉刷新会卡。你试试，一下拉就会ANR！

**Comment by 00Zion00** [comment]
hello，UI线程里加载数据？不存在的，那是封装的网络层回调，你可以点进去看一下 HttpManager。

**Comment by taany6210** [comment]
但是卡啊  你试过没 下拉刷新下就卡死了

**Comment by taany6210** [comment]
是的，加载数据我是看错了，但是确实是下拉刷新后就卡住动不了了，我看看是撒原因

**Comment by 00Zion00** [comment]
其实加载数据有个dialog的，不过没带背景，有时候不显眼，可能是dialog所以触摸没反应这个原因，还有就是banner是第三方控件，加载时可能显示空白

**Comment by taany6210** [comment]
我查出来了，不是dialog的原因  dialog能看到，是你的banner的原因。去掉banner就好了

**Comment by 00Zion00** [comment]
这个 banner 挺炫酷的，但是占用资源很多，也有一些 bug，当时想用是因为图片都是竖屏的，普通的banner 会让图片变形，后面有精力可以自己实现一个。
