### ISSUE TITLE
无法显示内容

### ISSUE THREAD

**Issue by ncguobiao** [123lxw123/VideoWorld_Android#11]
![image](https://user-images.githubusercontent.com/20988969/41267751-41da68d0-6e2f-11e8-8abc-6cb2f896b7ec.png)
真机，wifi,4G都正常

**Comment by 00Zion00** [comment]
服务器迁到阿里云了，主机地址变了

**Comment by 00Zion00** [comment]
主机地址    http://blockchain-core.top:8080/VideoWorld/
