### ISSUE TITLE
酷安市场下不了

### ISSUE THREAD

**Issue by kite8** [123lxw123/VideoWorld_Android#20]
大佬你好，我这边在浏览器里搜索 影视天地 + 酷安能搜到4.0的版本，但是点进去，就说没有，然后跳转到首页，我安装了酷安市场之后，就根本搜不到影视天地，大佬能否发个release版本，或者我的邮箱，谢谢了996845018@qq.com

**Comment by 00Zion00** [comment]
最近酷安审核严格，影视天地被下架了，可以 QQ群 126257036 下载
