### ISSUE TITLE
怎么打包变成安卓客户端啊

### ISSUE THREAD

**Issue by sky-daiji** [123lxw123/VideoWorld_Android#24]

**Comment by 00Zion00** [comment]
Android Studio 打开项目，菜单栏 Build -> Build Bundle(s)/APK(s)-> Build APK(s) 可生成测试安装包，如果需要打正式版则 菜单栏 Build ->Generate Signed Bundle or APK，选择 APK，点击下一步，选择签名文件，输入密码、别名，下一步，选择 release，勾选 v1、v2，点击 Finish 即可
