### ISSUE TITLE
主页一片空白，除了最后一页，每页都是“未知错误”

### ISSUE THREAD

**Issue by NanyangTaiji** [123lxw123/VideoWorld_Android#25]

**Comment by NanyangTaiji** [comment]
android-support-v4/KeyEventCompat.java depreciated, you need to update it.

**Comment by 00Zion00** [comment]
https://github.com/123lxw123/VideoWorld_Android/blob/master/Release Apk/影视天地-V4.1.3.apk
可以下载最新版试试，如果是自己编译的话由于 api 没有开源，所以编译出来会请求失败
