### ISSUE TITLE
源文件缺失啊 老铁

### ISSUE THREAD

**Issue by voynich-chen** [123lxw123/VideoWorld_Android#3]
import com.lxw.videoworld.app.config.Constant;
import com.lxw.videoworld.framework.application.BaseApplication;
都没有啊 老铁

**Comment by fanpeihua** [comment]
我的也一样

**Comment by baiheng222** [comment]
缺不少呢，
MainActivity消失了。。。。。

**Comment by 00Zion00** [comment]
查看 ignore 文件，里面是缺失的文件列表。
thunder module 源于 github 开源项目 https://github.com/oceanzhang01/MiniThunder
由于资源来自互联网并没有版权，仅供学习交流，不过之前有人把前后端代码用于商业用途，为了避免不必要的麻烦，所以把核心文件忽略了。

**Comment by quert999** [comment]
thunder module这个开源项目已经404了。。

**Comment by 00Zion00** [comment]
不存在的，识别的链接里多了个句号，修改好了你再试下。

**Comment by 00Zion00** [comment]
补全了忽略的文件
