### ISSUE TITLE
无法编译过

### ISSUE THREAD

**Issue by bbjsmart** [123lxw123/VideoWorld_Android#8]
1.   > Could not resolve project :thunder.
     Required by:
         project :app
      > Unable to find a matching configuration of project :thunder: None of the consumable configurations have attributes.

2. import com.lxw.videoworld.framework.application.BaseApplication;
 没有找到com.lxw.videoworld.framework.applicatio这个文件夹

**Comment by 00Zion00** [comment]
#3 了解一下
